### ISSUE TITLE
[Feature Request]  SABnzbd/NZBget Integration

### ISSUE THREAD

**Issue by MotherTrucker** [Archmonger/Conreq#11]
**Is your feature request related to a problem? Please describe.**
Not a problem with a bug.

**Describe the feature you'd like**
For Conreq to show the "status" of a downloaded show. ie; Place in the queue, Percent downloaded, Importing, Possibly even an estimated timeframe based on the estimates Sab gives (Not sure if that can be broken down per file as Sab only provides the estimation for the entire queue) 

**Are there any possible alternatives?**
Organizr, Radarr, and Sonarr can all display some of this information, so possibly polling them for basic info could be a workaround.

**Additional context**
The number 1 question I am asked from users is when the requested movie/tv show will be done. Often I have 10+items in the queue, and I am the only one who actually knows when things will be done. I think providing the visual "here's the status" will help general users to feel more comfortable with the technology.

**Comment by Alcatraz077** [comment]
This would be neat, considering *arr's generally have a progress bar for items being downloaded in the "queue" section of the app, I think it could be implemented (though I'm not the main dev or anything). 

Also @MotherTrucker , when you used number 1, it linked to a closed issue.

**Comment by Archmonger** [comment]
Progress bars are definitely possible through the arr API. I had some stubs put in during alpha but never implemented any further. I'll add it to be considered for V1.

**Comment by MotherTrucker** [comment]
> This would be neat, considering *arr's generally have a progress bar for items being downloaded in the "queue" section of the app, I think it could be implemented (though I'm not the main dev or anything).
> 
> Also @MotherTrucker , when you used number 1, it linked to a closed issue.

Shoot, definitely didn't mean to do that! Thanks for the heads up though

**Comment by MotherTrucker** [comment]
> Progress bars are definitely possible through the arr API. I had some stubs put in during alpha but never implemented any further. I'll add it to be considered for V1.

Does the call have to come through an *arr API? Is configuration with SAB or NZBget out of the question? Just curious, I want to know where I may provide some benifit to focus some effort at this.

**Comment by Archmonger** [comment]
It's highly recommend to have them come from the arrs.

If you get them straight from the downloaders you'll need to parse out thing that weren't grabbed by arrs, or even potentially things grabbed by other arr instances. Additionally we'd need to develop support for every major downloader. It would get super messy, given the countless number of use cases available.

I would personally implement this as a simple "currently downloading" tab that just pops out whatever is in the arr queue. Would be the quickest and cleanest development path.

**Comment by Archmonger** [comment]
This issue is being closed in favor of moving all feature requests to Github Discussions. 

Please create a post here:
[https://github.com/Archmonger/Conreq/discussions/categories/feature-requests](https://github.com/Archmonger/Conreq/discussions/categories/feature-requests)
