### ISSUE TITLE
Base URL not being added to static URLs

### ISSUE THREAD

**Issue by Dreytac** [Archmonger/Conreq#14]
**Describe the bug**
Static URL's are not being generated with the BASE_URL part added. URL's are being generated as "src=/static/....." instead of the expected "src=/BASE_URL/static/.....".

Obviously the access log doesn't show the static URL's are being hit as they're not passed through the reverse proxy.

**To Reproduce**
1. Install either Selfhosters or Hotio's Docker image on Unraid.
2. Add "BASE_URL" as a container variable with "requests" being the value.
2. Setup reverse proxy to send "https://your.site.here/requests" to Conreq.
3. Access Conreq using "https://your.site.here/requests".

**Expected behavior**
Base URL to be prepended to all URL's on the page and Conreq to render properly.

**Additional context**
Issue occurs with both Selfhosters and Hotio's containers. Occurs on both "latest" and "develop" tags.

### System Information
**Conreq Version**
 - Version: Unknown
 - Branch: Both main and develop
 - Host: Unraid Docker, both Selfhosters and Hotio's.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome

**Comment by Archmonger** [comment]
Thanks for the issue report. I'll replicate and bug fix this soon.

**Comment by Dreytac** [comment]
A cursory glance over the code and it appears the issue is that static URL's are generated in the "settings.py" file while BASE_URL is set in "urls.py". Adding the base URL to STATIC_URL in "settings.py" appears to fix the issue (can't use get_base_url() though).

Hope that helps a bit.

**Comment by Archmonger** [comment]
A patch has been pushed to `develop`.
Please validate that it works whenever you have a chance.

Thanks!

**Comment by Dreytac** [comment]
The fix works like a charm!

Thanks for the quick response and fix!
