### ISSUE TITLE
Mobile Browser UI Issue

### ISSUE THREAD

**Issue by CassTG** [Archmonger/Conreq#49]
**Describe the bug**

Various Ui issues on Samsung Browser and Edge Browser Mobile on s21 Ultra
Including icons not observing correct margins and padding on text elements in menu system

**To Reproduce**

1. Open Samsung browser
2. Navigate to Offcanvas Menu

**Expected behavior**
Correct UI Layout

**Additional context**
Tried to override with custom css by placing file in /static/custom.css however it was ignoring all changes

### System Information

**Conreq Version**
 - Version: [0.19.7]
 - Branch: [Nightly]
 - Host: [Ubuntu Minimal 20.04, with Docker only, behind linuxserver.io Swag Proxy / ssl, tested on Hotio docker]

**Smartphone**
 - Device: [Samsung S21 Ultra]
 - OS: [Android 11, Oneui 3.1]
 - Browser: [Samsung Browser and Microsoft Edge Mobile]

**Comment by Archmonger** [comment]
Thanks for the issue report, will try to get to this soon!

**Comment by Archmonger** [comment]
@CassTG Pushed a fix to develop (v0.19.16). Please validate the fix when you get a chance!
