### ISSUE TITLE
[Feature Request] Support Lidarr & LazyLibrarian

### ISSUE THREAD

**Issue by Protektor-Desura** [Archmonger/Conreq#7]
It would be nice if you supported Lidarr for requesting music. It would also be nice if you supported LazyLibrarian for requesting ebooks, audiobooks, magazines and comic books. Jellyfin has full support for audiobooks, ebooks, magazines and comic books.

One thing to keep in mind for the future would be supporting Readarr once it gets further beyond alpha development for ebooks/etc.

**Comment by Archmonger** [comment]
Lidarr support is coming soon. 

I'd need to do some more investigation as to whether ebook requesting is viable.

**Comment by Archmonger** [comment]
This issue is being closed in favor of moving all feature requests to Github Discussions. 

Please create a post here:
[https://github.com/Archmonger/Conreq/discussions/categories/feature-requests](https://github.com/Archmonger/Conreq/discussions/categories/feature-requests)
