### ISSUE TITLE
[Feature Request]  --Add Separate Manager for Animes--

### ISSUE THREAD

**Issue by ma-karai** [Archmonger/Conreq#9]
I have always separated Animes and TV-shows with two separate Sonarr instances as well as a Radarr and Animarr instance for movies.  This helps me to keep everything better-organized, and it keeps the super slow databases faster.

It would be fantastic if this could be added. I am aware that this request might be quite personalized, and not a lot of people do it this way, but honestly, I don't see a drawback for other people, and only a potential upside for some individuals.

**Comment by Archmonger** [comment]
Currently there are no plans to support multiple sonarr/radarr instances.

We do, however, have plans for the user to be able to optionally use a Conreq integrated grabber. This will have significantly higher performance than the arrs due to MySQL (or any other Conreq supported database backend).
